# Generated by Django 6.0.5 on 2026-06-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to='users/'),
        ),
    ]
